[package]
name = "foobar2000-catbox"
version = "1.0.7"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 16

[dependencies]
base64 = "0.22.1"

[dependencies.serde]
version = "1.0.217"
default-features = false
features = ["derive"]

[dependencies.serde_yml]
version = "0.0.12"

[dependencies.strum]
version = "0.26.3"
default-features = false
features = ["strum_macros"]

[dependencies.strum_macros]
version = "0.26.4"

[dependencies.curl]
version = "0.4.47"

[dependencies.image]
version = "0.25.5"
default-features = false
features = ["png", "jpeg", "webp"]
