# settings.yml

# --- LITTERBOX
# Use this with caution. After the set expiration time has passed, the saved link will break,
# and foo_discord_rich will be none the wiser.
enable_litterbox: false       # Options (boolean): true or false

# LITTERBOX EXPIRE TIME
# After how many hours the file will be removed from their system.
litterbox_expire_time: "24h" # Options (string, case-sensitive): "1h", "12h", "24h", "72h"

# --- IMAGE ENCODING
# Enables re-encoding of album art, offerring further quality and file size
# balancing options.
enable_encode: false         # Options (boolean): true or false

# IMAGE ENCODING FORMAT
# Specifies the output format to encode the album art in.
encode_format: "JPG"         # Options (string, case-sensitive): "JPG", "PNG", "WEBP"

# IMAGE ENCODING FORMAT QUALITY
# Defines the level of quality to use on the encoded image. Note that this is
# currently only applicable when using the JPG format!
encode_format_quality: 80    # Options (number): from 1 (lower quality, smaller and faster) to 100 (higher quality, larger and slower)

# --- IMAGE RESIZING
# When enabled, album art exceeding the defined resize_max_resolution values on any
# side will be scaled down to fit within these specified limits while preserving the
# original aspect ratio.
enable_resize: true          # Options (boolean): true or false

# IMAGE RESIZING MAXIMUM RESOLUTION
# Sets the desired width and height to scale images to. You must use power-of-two
# values (e.g., 2^n = 512, 1024, etc.).
resize_max_resolution:       # Options (sequence): width and height
    - 1024                   # Width (number)
    - 1024                   # Height (number)

# USER HASH
# Associate your uploaded images with your registered Catbox account. Uncomment the following
# line by removing the # symbol, and replace the existing hash with your own. You can get
# your user hash from https://catbox.moe/user/manage.php while logged in, and replace the following
# example below with your own.
# user_hash: "f3c9a4e81d2b76f59e40c8a3d"

# --- MISCELLANEOUS
user_agent: "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
