name: Coverage

permissions:
  contents: read

sudo: required

on:
    push:
        branches: ["development"]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Compile
              run: cargo test --no-run
            - name: Run kcov on test binary
              uses: sudo-bot/action-kcov@latest
              with:
                cli-args: "--dump-summary --include-pattern=./src --exclude-pattern=./tests,target ./coverage/ ./target/debug/deps/foobar2000_catbox-*"
            - name: Upload coverage report
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                directory: ./coverage/
                fail_ci_if_error: true