name: Rust

on:
    push:
        branches: ["development"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout from repository
              uses: actions/checkout@v4
            - name: Compile the application
              run: cargo build
            - name: Run multiple samples
              run: |
                for sample in ./samples/*.jpg; do
                  echo "$sample" | ./target/release/foobar2000-catbox
                done